persons:
  - id: 5812290
    name: Oleg
    surname: Tinkov
    middle_name: Urievich
    date_of_birth: 1971-01-01
    gender: true
  - id: 5231652
    name: Ignat
    surname: Yakovlev
    middle_name: Igorevic
    date_of_birth: 2014-04-03
    gender: true
  - id: 4604129
    name: dwedwe
    surname: dwedwe
    middle_name: dwedwe
    date_of_birth: 2008-05-04
    gender: true
  - id: 1407872
    name: Makar
    surname: timofeev
    middle_name: Alekseevich
    date_of_birth: 2014-05-11
    gender: true
  - id: 2877343
    name: Maria
    surname: Yakovleva
    middle_name: Olegovna
    date_of_birth: 2001-06-21
    gender: falsesw
  - id: 6796876
    name: Nikita
    surname: Hrushov
    middle_name: Sergeevich
    date_of_birth: 1955-06-15
    gender: true
  - id: 1927737
    name: Ivan
    surname: Koshkin
    middle_name: Vasilevich
    date_of_birth: 2010-06-19
    gender: true
  - id: 1111111
    name: Maksim
    surname: Ivanov
    middle_name: Petrovich
    date_of_birth: 2001-01-01
    gender: true
  - id: 1277517
    name: Pavel
    surname: Gavrilov
    middle_name: Mikhailovic
    date_of_birth: 1997-08-15
    gender: true
  - id: 4324234
    name: Elena
    surname: Golovina
    middle_name: Dmitrievna
    date_of_birth: 1998-03-29
    gender: false
